### ISSUE TITLE
Implement transactions

### ISSUE THREAD

**Issue by relmay** [relmay/plutonio#1]
## TODO
- [ ] Income transactions
- [ ] Outcome transactions
- [ ] Transaction categories
- [ ] Account balance update
- [ ] Get all transactions for the last month 
- [ ] Get transactions by category
