### ISSUE TITLE
Implement balance

### ISSUE THREAD

**Issue by relmay** [relmay/plutonio#2]
## TODO
- [ ] Get current balance of specified account
- [ ] Get current balance of all accounts in different currencies
- [ ] Get current balance of all accounts in one currency
